source 'https://rubygems.org'

gem 'bourbon'
gem 'coffee-script'
gem 'guard'
gem 'guard-jekyll-plus'
gem 'guard-livereload'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-gh-pages'
gem 'jemoji'
gem 'neat'
gem 's3_website'
gem 'sass'
gem 'thin'
gem 'uglifier'
